spring:
  application:
    name: shop-inn
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB


server:
  servlet:
    context-path: /shop-inn/v1/

springdoc:
  default-produces-media-type: application/json